### ISSUE TITLE
No need of new function, since you are doing a proxy here 

### ISSUE THREAD

**Issue by lucastschmidt** [lucazpinheiro/card-trick#5]
https://github.com/lucazpinheiro/card-trick/blob/33e10a405cc5dacd0b480ea108ed0cc057b96b29/src/components/Display.jsx#L67

**Comment by lucazpinheiro** [comment]
passing 'setRow' as props without a proxy function won't trigger the function whent the component render?

**Comment by lucazpinheiro** [comment]
Fixed
